### PR TITLE
Add translation token "mycourses"

### PR DESCRIPTION
**Pull request by nadavkav**
Convert hard coded English text:"My courses" to use moodle.php "mycourses" translation token.

### CODE REVIEW

**Comment by hitteshahuja** [comment]
Hi Nadav,
Many thanks for this. This has now been merged ;)

**Comment by nadavkav** [comment]
Sweet :-)

I have some more RTL fixes and other stuff too, I will soon send some more PR.
btw, what a beautiful and useful plugin!

**Comment by hitteshahuja** [comment]
thanks, I'm working on a AMD version of the JS for Moodle 2.9+ . Any contributions ( lang strings or otherwise are welcome) https://github.com/hitteshahuja/moodle-block_searchcourses/tree/MOODLE_29

**Comment by nadavkav** [comment]
Beautiful news!

As I am the Hebrew translation maintainer of Moodle, I have already updated the block_searchcourses version 2.7 Hebrew translation string on the lang.moodle.org (AMOS). And so, looking forward for you updating the 2.9 version so I can updated that translation too, as I have install your current block_searchcourses version 2.7 on our Moodle 2.9 system.

**Comment by hitteshahuja** [comment]
Great ! Yes, I remember speaking to you this year in Dublin  :smile: . we spoke briefly about git and rebasing .I'm guessing the introduction of AMD shouldn't affect the lang strings but if there any additions i'll give you a heads up !

**Pull request merged**
